# Generated by Django 5.2.9 on 2025-12-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side1', models.TextField(default='Szeretettel üdvözöljük!')),
                ('side2', models.TextField(blank=True, default='', null=True)),
                ('side3', models.TextField(blank=True, default='', null=True)),
                ('side2_image', models.ImageField(blank=True, null=True, upload_to='wedding_images/')),
                ('side3_image', models.ImageField(blank=True, null=True, upload_to='wedding_images/')),
            ],
            options={
                'verbose_name': 'Esküvői beállítás',
                'verbose_name_plural': 'Esküvői beállítások',
            },
        ),
    ]
